#!/bin/bash
# This will load the siesta/4.1-b2/impi-5/intel-16/4.1-b2-2
module purge
module load intel/16
module load impi
module load fftw3/3.3/impi-5
module load siesta

echo "The following SIESTA version has been loaded: siesta/4.1-b2/impi-5/intel-16/4.1-b2-2"
module list
