#!/bin/bash
rm *out
rm *XV
rm *ion*
rm fdf-*
rm core*
rm *KP
rm *BONDS*
rm *CLOCK MESSAGES
rm *DIST*
rm *OUT
rm *INDX
rm *bib
rm *LIST
rm *DM
rm *DOS*
rm *TIME*
rm *time*
rm *VT*
rm *VH*
rm *EIG*
rm *STRESS*
rm *yml*
rm *ENTHALPY*
rm *FA*
rm *ANI
rm *CG
rm *PLD
rm *RHO
rm *WFSX
rm *MD
rm *MD_CAR
rm *MDE
rm *NEXT_ITER
rm *HSX
rm *DIM

echo "Done cleaning..."
echo "INPUT_TMP* files are left alone to keep track of previous runs"
