#!/bin/bash

file_name="md_forces.era"
mes="Logging all Total MD forces per MD step"

echo $mes > ${file_name}
echo $mes

for f in */ ; do
  cd $f
  echo "Now looking in $f"
  echo "Now looking in $f" >> ../${file_name}
  var=$(grep "Tot   " *out)
  echo "$var" >> ../${file_name}
  echo "$var"
  cd ..
done

echo "Find the file ./${file_name}"
echo "Look for 'siesta:    Tot'  to see if converged"
