#!/bin/bash

$file_name="md_resforces.era"
mes="Logging all resolutions for MD forces"

echo $mes > ${file_name}
echo $mes

for f in */ ; do
  cd $f
  echo "Now looking in $f"
  echo "Now looking in $f" >> ../${file_name}
  var=$(grep "Res" *out)
  echo "$var" >> ../${file_name}
  echo "$var"
  cd ..
done

echo "Find the file ./${file_name}"
