#!/bin/bash

echo "Logging all MD forces" > md_moves.era
echo "Logging all MD forces"

for f in */ ; do
  cd $f
  echo "Now looking in $f"
  echo "Now looking in $f" >> ../md_forces.era
  moves=$(grep -A 2 "Atomic forces" *out)
  echo "$moves" >> ../md_forces.era
  echo "$moves"
  cd ..
done

echo "Find the file ./md_forces.era" 
