#!/bin/bash

# argument format: 
#  $0: grep_for  # defines the action 
#  $1: file_name_to_write
#  

#
#if [ "$0" != "" ]; then
#    file_name="md_forces.era"
#    mes="Logging all Total MD forces per MD step"
#else
#    echo "Positional parameter 1 is empty"
#fi

#Init if statements

if [ "$1" == "Tot_force" ]; then
    file_name="md_forces.era"
    mes="Logging all Total MD forces per MD step"
fi

if [ "$1" == "Res_force" ]; then
    file_name="md_resforces.era"
    mes="Logging all resolutions for MD forces"
fi

if [ "$1" == "Times" ]; then
    file_name="times.era"
    mes="SIESTA caclculation times"
    mes=$"${mes}\nCalc: wall_time  cpu_time"
fi

if [ "$1" == "Moves" ]; then
    file_name="moves.era"
    mes="Logging all MD moves"
fi

# Intitialize to overwrite file here
echo $mes > ../${file_name}

# The for loop
for f in */ ; do
  cd $f
  
  #Init if statements
  if [ "$1" == "Tot_force" ]; then
    echo "Now looking in $f" | tee -a ../${file_name}
    var=$(grep "Tot   " *out)
    echo "$var" | tee -a ../${file_name}  
  fi
  
  if [ "$1" == "Res_force" ]; then
    echo "Now looking in $f" | tee -a ../${file_name}
    var=$(grep "Res" *out)
    echo "$var" | tee -a ../${file_name}
  fi

  if [ "$1" == "Times" ]; then
    calc=$(echo $f | cut -d ^ -f 1)
    wallt=$(grep wall TIMES | tr -s ' ' | cut -d = -f 2)
    cput=$(grep Calc: TIMES | cut -d = -f 2 | tr -s ' ' | cut -d ' ' -f 2)
    echo "$calc: $wallt  $cput" | tee -a ../${file_name}
  fi
  
  if [ "$1" == "Moves" ]; then
    echo "Now looking in $f" | tee -a ../${file_name}
    var=$(grep move *out)
    echo "$var" | tee -a ../${file_name}
  fi  
  
  cd ..
done


echo "" | tee -a ../${file_name}
echo "Find the file ./${file_name}"

#Specific End Messages
if [ "$1" == "Tot_force" ]; then
  echo "Look for 'siesta:    Tot'  to see if converged" | tee -a ../${file_name}
fi

if [ "$1" == "Res_force" ]; then
  echo "" | tee -a ../${file_name}
fi

if [ "$1" == "Times" ]; then
  echo "" | tee -a ../${file_name}
fi


echo "" | tee -a ../${file_name}
echo "Done" | tee -a ../${file_name}
